# 1. Site settings in the templates via {{ site.myvariable }}.
title: Portfolio | Seork
email: seork.art@gmail.com
description: Découvrez le portfolio de Seork, artiste graffeur basé à Montréal, Canada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.seork.fr" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8
lang: fr-FR
repo: "https://github.com/Amanda-Martinez/seork"

# 2. Site navigation
navigation_header:
  Accueil: /

navigation_footer:
  Mentions légales: /mentions-legales
  Plan du site: /plan-du-site

social_links:
  Instagram: https://www.instagram.com/seork.art/

# 3. Build settings
markdown: kramdown

# 4. Jekyll settings
permaling: ""
timezone: America/Canada

# 5. Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Mon portfolio"
    feature_text: |
      Bienvenue sur mon portfolio
    feature_image: "https://unsplash.it/1300/400?image=1067"
